server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  thymeleaf:
    cache: false
  data:
    mongodb:
      uri: mongodb://192.168.0.148:27017/bjcj
udp:
  port: 16662
  open: true
log:
  grid_id: -1
  raw_path: ${log.dicPath}/rows_${log.grid_id}.log
  loc_result_path: ${log.dicPath}/locresult_${log.grid_id}.log
  record_path: ${log.dicPath}/record_${log.grid_id}.log
  dicPath: C:/log/3-26-${random.int}
  open: true
  x: 27
  y: 14.3
  #1
#  x: 21.5d
#  y: 17.3d
#2
#  x: 23.5d
#  y: 14.3d

#3  唐总办公室
#  x: 30d
#  y: 17.8d
#4 信号差  王总办公室
#  x: 37d
#  y: 18.8d

#5 会议室 信号差 苹果5G
#  x: 34d
#  y: 7.8d

#6
#  x: 18.5d
#  y: 13.3d

#7
#  x: 16.5d
#  y: 18.3d

#  x: 19.5d  #70-71
#  y: 14.3d

#  x: 16.5d
#  y: 19.3d

#  x: 16.5d
#  y: 13.3d


default:
  algorithmConf:
    sliding_window_time: 180
    sliding_step_time: 10
    k: 6
    not_null_val_min_count: 2
  apConf:
    info:
      - mac: 70476002a30b
        x: 35
        y: 6.3
      - mac: 70476002a30c
        x: 39
        y: 9.3
      - mac: 70476002a30d
        x: 33
        y: 16.3
      - mac: 70476002a30e
        x: 17
        y: 14.3
      - mac: 70476002a30f
        x: 22
        y: 19.3
      - mac: 70476002a30a
        x: 27
        y: 13.8

  messageConf:
    type:
      00: direct-wifi
      01: direct-ap
      02: ssid
      03: wifi-rssi
      04: wifi-csi
      05: indirect-wifi
      06: indirect-ap
    rssi-min: -110
    mac-allow:
##        - 240995b2909c #旧荣耀
        - 8844771b6789 #华为mate9
#        - 34d712a2e3dc #锤子
#        - e4b2fbe3cd32  #huawei p8
##        - 708a096219a1 #徐磊
        - 00cdfe012d4c #苹果
    mac-refuse:
